
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package fes.aragon;

/** CUP generated class containing symbol constants. */
public class Simbolo {
  /* terminals */
  public static final int ftitle = 5;
  public static final int palabra = 13;
  public static final int ihtml = 2;
  public static final int ibody = 8;
  public static final int EOF = 0;
  public static final int ih1 = 10;
  public static final int numero = 12;
  public static final int ihead = 6;
  public static final int fhtml = 3;
  public static final int fbody = 9;
  public static final int error = 1;
  public static final int fh1 = 11;
  public static final int fhead = 7;
  public static final int ititle = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ihtml",
  "fhtml",
  "ititle",
  "ftitle",
  "ihead",
  "fhead",
  "ibody",
  "fbody",
  "ih1",
  "fh1",
  "numero",
  "palabra"
  };
}

